import SwiftUI

/// On-demand "System Report" generated by Sonnet from the current items +
/// graph state. Markdown rendered inline; the user can copy the text.
struct HealthReportView: View {
    @EnvironmentObject var appState: AppState
    @StateObject private var aiConfig = AIConfiguration.shared

    @State private var report: HealthReportGenerator.Report?
    @State private var isGenerating = false
    @State private var statusMessage: String?

    var body: some View {
        VStack(spacing: 0) {
            header
            Divider()
            content
            Divider()
            footer
        }
        .frame(minWidth: 720, minHeight: 600)
    }

    // MARK: - Sections

    private var header: some View {
        HStack(spacing: 12) {
            Image(systemName: "doc.text.magnifyingglass")
                .font(.title2)
                .foregroundColor(.accentColor)
            VStack(alignment: .leading, spacing: 2) {
                Text("System Report")
                    .font(.title2)
                    .fontWeight(.semibold)
                Text("AI-written narrative on this Mac's persistence posture.")
                    .font(.caption)
                    .foregroundColor(.secondary)
            }
            Spacer()
            if aiConfig.isAIActive {
                Text("AI calls today: \(aiConfig.callsTodayCount) / \(aiConfig.dailyCallCap)")
                    .font(.caption)
                    .foregroundColor(.secondary)
            }
        }
        .padding(16)
    }

    @ViewBuilder
    private var content: some View {
        if !aiConfig.isAIActive {
            placeholder(
                icon: "brain",
                title: "AI is not active",
                detail: "Enable AI in Settings → AI and provide a valid API key."
            )
        } else if let report = report {
            ScrollView {
                VStack(alignment: .leading, spacing: 12) {
                    HStack(spacing: 8) {
                        Image(systemName: "clock")
                            .foregroundColor(.secondary)
                        Text("Generated \(formattedDate(report.generatedAt)) · \(report.inputItemCount) items analyzed")
                            .font(.caption)
                            .foregroundColor(.secondary)
                    }
                    Text(LocalizedStringKey(report.markdown))
                        .textSelection(.enabled)
                        .frame(maxWidth: .infinity, alignment: .leading)
                }
                .padding(16)
            }
        } else if isGenerating {
            VStack(spacing: 12) {
                ProgressView()
                Text("Sonnet is writing the report…")
                    .font(.caption)
                    .foregroundColor(.secondary)
                Text("This usually takes 10-20 seconds.")
                    .font(.caption2)
                    .foregroundColor(.secondary)
            }
            .frame(maxWidth: .infinity, maxHeight: .infinity)
        } else {
            placeholder(
                icon: "doc.text.magnifyingglass",
                title: "No report yet",
                detail: "Click 'Generate report' below to ask Sonnet to write a narrative health summary of this Mac's persistence posture. Costs ~$0.05-0.10 per call."
            )
        }
    }

    private var footer: some View {
        HStack(spacing: 12) {
            if let status = statusMessage {
                Text(status)
                    .font(.caption)
                    .foregroundColor(.secondary)
            }
            Spacer()
            if let report = report {
                Button {
                    NSPasteboard.general.clearContents()
                    NSPasteboard.general.setString(report.markdown, forType: .string)
                    statusMessage = "Copied to clipboard"
                } label: {
                    Label("Copy markdown", systemImage: "doc.on.doc")
                }
            }
            Button {
                Task { await generate() }
            } label: {
                if isGenerating {
                    HStack(spacing: 6) {
                        ProgressView().controlSize(.small)
                        Text("Generating…")
                    }
                } else {
                    Label(report == nil ? "Generate report" : "Regenerate", systemImage: "sparkles")
                }
            }
            .buttonStyle(.borderedProminent)
            .disabled(!canGenerate)
        }
        .padding(16)
    }

    private func placeholder(icon: String, title: String, detail: String) -> some View {
        VStack(spacing: 12) {
            Image(systemName: icon)
                .font(.system(size: 42))
                .foregroundColor(.secondary)
            Text(title)
                .font(.headline)
            Text(detail)
                .font(.caption)
                .foregroundColor(.secondary)
                .multilineTextAlignment(.center)
                .padding(.horizontal, 30)
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }

    // MARK: - Actions

    private var canGenerate: Bool {
        aiConfig.isAIActive && aiConfig.canMakeCall && !appState.items.isEmpty && !isGenerating
    }

    private func generate() async {
        isGenerating = true
        statusMessage = nil
        defer { isGenerating = false }

        do {
            let result = try await HealthReportGenerator.shared.generate(items: appState.items)
            report = result
            statusMessage = "Report generated · \(result.markdown.count) chars"
        } catch let err as HealthReportGenerator.ReportError {
            statusMessage = err.errorDescription
        } catch {
            statusMessage = "Report failed: \(error.localizedDescription)"
        }
    }

    private func formattedDate(_ date: Date) -> String {
        let f = DateFormatter()
        f.dateStyle = .medium
        f.timeStyle = .short
        return f.string(from: date)
    }
}
